CREATE TABLE news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    source VARCHAR(255),
    link VARCHAR(500),
    image VARCHAR(500)
);

CREATE TABLE bangkok_scoop_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    source VARCHAR(255),
    link VARCHAR(500),
    image VARCHAR(500)
);

TRUNCATE TABLE news;
TRUNCATE TABLE bangkok_scoop_news;

ALTER TABLE news
ADD CONSTRAINT uq_news_link UNIQUE (link);

ALTER TABLE bangkok_scoop_news
ADD CONSTRAINT uq_bangkok_scoop_news_link UNIQUE (link);