-- Drop old tables
DROP TABLE IF EXISTS bangkok_news;
SELECT 'Dropped table bangkok_news' AS debug_msg;

DROP TABLE IF EXISTS pattaya_news;
SELECT 'Dropped table pattaya_news' AS debug_msg;

DROP TABLE IF EXISTS phuket_news;
SELECT 'Dropped table phuket_news' AS debug_msg;

DROP TABLE IF EXISTS news;
SELECT 'Dropped table news' AS debug_msg;

DROP TABLE IF EXISTS bangkok_scoop_news;
SELECT 'Dropped table bangkok_scoop_news' AS debug_msg;

DROP TABLE IF EXISTS thailand_island_news;
SELECT 'Dropped table thailand_island_news' AS debug_msg;

DROP TABLE IF EXISTS thai_lady_date_finder;
SELECT 'Dropped table thai_lady_date_finder' AS debug_msg;

DROP TABLE IF EXISTS find_thai_property;
SELECT 'Dropped table find_thai_property' AS debug_msg;

DROP TABLE IF EXISTS legally_married_in_thailand;
SELECT 'Dropped table legally_married_in_thailand' AS debug_msg;

DROP TABLE IF EXISTS wedding_boutique_phuket;
SELECT 'Dropped table wedding_boutique_phuket' AS debug_msg;

DROP TABLE IF EXISTS trailhead_thailand;
SELECT 'Dropped table trailhead_thailand' AS debug_msg;

-- Create tables
CREATE TABLE bangkok_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    source VARCHAR(100000),
    link VARCHAR(500) UNIQUE,
    image VARCHAR(500),
    PUBLISHED_DATE VARCHAR(500)
);
SELECT 'Created table bangkok_news' AS debug_msg;

CREATE TABLE pattaya_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    description VARCHAR(100000),
    link VARCHAR(500) UNIQUE,
    image_url VARCHAR(500),
    PUBLISHED_DATE VARCHAR(500)
);
SELECT 'Created table pattaya_news' AS debug_msg;

CREATE TABLE phuket_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    description VARCHAR(100000),
    link VARCHAR(500) UNIQUE,
    image_url VARCHAR(500),
    PUBLISHED_DATE VARCHAR(500)
);
SELECT 'Created table phuket_news' AS debug_msg;

CREATE TABLE news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    source VARCHAR(255),
    link VARCHAR(500) UNIQUE,
    image VARCHAR(500)
);
SELECT 'Created table news' AS debug_msg;

CREATE TABLE bangkok_scoop_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    source VARCHAR(255),
    link VARCHAR(500) UNIQUE,
    image VARCHAR(500)
);
SELECT 'Created table bangkok_scoop_news' AS debug_msg;

CREATE TABLE thailand_island_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    source VARCHAR(255),
    link VARCHAR(500) UNIQUE,
    image VARCHAR(500)
);
SELECT 'Created table thailand_island_news' AS debug_msg;

CREATE TABLE thai_lady_date_finder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    source VARCHAR(255),
    link VARCHAR(500) UNIQUE,
    image VARCHAR(500)
);
SELECT 'Created table thai_lady_date_finder' AS debug_msg;

CREATE TABLE find_thai_property (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    source VARCHAR(255),
    link VARCHAR(500) UNIQUE,
    image VARCHAR(500)
);
SELECT 'Created table find_thai_property' AS debug_msg;

CREATE TABLE legally_married_in_thailand (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    source VARCHAR(255),
    link VARCHAR(500) UNIQUE,
    image VARCHAR(500)
);
SELECT 'Created table legally_married_in_thailand' AS debug_msg;

CREATE TABLE wedding_boutique_phuket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    source VARCHAR(255),
    link VARCHAR(500) UNIQUE,
    image VARCHAR(500)
);
SELECT 'Created table wedding_boutique_phuket' AS debug_msg;

CREATE TABLE trailhead_thailand (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    source VARCHAR(255),
    link VARCHAR(500) UNIQUE,
    image VARCHAR(500)
);
SELECT 'Created table trailhead_thailand' AS debug_msg;

SCRIPT TO 'schema-dump.sql';
